package id.ac.poliban.fenia.listviewpahlawan;

import java.util.ArrayList;
import java.util.List;

public class DataPahlawan {
    static List<Pahlawan> getAllPahlawan(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/486px-Sudirman.jpg", "Soedirman", "Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 – meninggal 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Diponegoro.jpg/220px-Diponegoro.jpg", "Pangeran Diponegoro", "Pangeran Diponegoro adalah putra sulung dari Sultan Hamengkubuwana III, raja ketiga di Kesultanan Yogyakarta. Lahir pada tanggal 11 November 1785 di Yogyakarta dengan nama Mustahar dari seorang selir bernama R.A. Mangkarawati, yaitu seorang garwa ampeyan (istri selir) yang berasal dari Pacitan. Semasa kecilnya, Pangeran Diponegoro bernama Bendara Raden Mas Antawirya."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tjoet_Nya%27_Dhien.jpg/220px-Tjoet_Nya%27_Dhien.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Portret_van_Tuanku_Imam_Bonjol.jpg/220px-Portret_van_Tuanku_Imam_Bonjol.jpg", "Tuanku Imam Bonjol", "Tuanku Imam Bonjol (lahir di Bonjol, Pasaman, Sumatra Barat, Indonesia, 1772 - wafat dalam pengasingan dan dimakamkan di Lotta, Pineleng, Minahasa, 6 November 1864) adalah salah seorang ulama, pemimpin dan pejuang yang berperang melawan Belanda dalam peperangan yang dikenal dengan nama Perang Padri pada tahun 1803-1838.[1] Tuanku Imam Bonjol diangkat sebagai Pahlawan Nasional Indonesia berdasarkan SK Presiden RI Nomor 087/TK/Tahun 1973, tanggal 6 November 1973."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg/220px-Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg", "Ki Hajar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg", "Pattimura", "Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/c/c4/Achmad_soebardjo.jpg", "Achmad Soebardjo", "Mr. Raden Achmad Soebardjo Djojoadisoerjo (lahir di Karawang, Jawa Barat, 23 Maret 1896 – meninggal 15 Desember 1978 pada umur 82 tahun) adalah tokoh pejuang kemerdekaan Indonesia, diplomat, dan seorang Pahlawan Nasional Indonesia. Ia adalah Menteri Luar Negeri Indonesia yang pertama. Achmad Soebardjo memiliki gelar Meester in de Rechten, yang diperoleh di Universitas Leiden Belanda pada tahun 1933. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bung_Tomo.jpg/220px-Bung_Tomo.jpg", "Sutomo", "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Raden_Dewi_Sartika.jpg/220px-Raden_Dewi_Sartika.jpg", "Dewi Sartika", "Raden Dewi Sartika (Sunda: ᮛ᮪ᮓ᮪. ᮓᮦᮝᮤ ᮞᮁᮒᮤᮊ, Latin: Rd. Déwi Sartika; lahir di Cicalengka, Bandung, 4 Desember 1884 – meninggal di Cineam, Tasikmalaya, 11 September 1947 pada umur 62 tahun) adalah tokoh perintis pendidikan untuk kaum wanita. Ia diakui sebagai Pahlawan Nasional oleh Pemerintah Indonesia pada tahun 1966. "));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/f/ff/Gusti_ngurah_rai.jpg/220px-Gusti_ngurah_rai.jpg", "I Gusti Ngurah Rai", "Brigadir Jenderal TNI (Anumerta) I Gusti Ngurah Rai (lahir di Desa Carangsari, Petang, Kabupaten Badung, Bali, Hindia Belanda, 30 Januari 1917 – meninggal di Marga, Tabanan, Bali, Indonesia, 20 November 1946 pada umur 29 tahun) adalah seorang pahlawan Indonesia dari Kabupaten Badung, Bali.\n" +
                    "\n" +
                    "Ngurah Rai memiliki pasukan yang bernama pasukan \"Ciung Wanara\" yang melakukan pertempuran terakhir yang dikenal dengan nama Puputan Margarana. (Puputan, dalam bahasa bali, berarti \"habis-habisan\", sedangkan Margarana berarti \"Pertempuran di Marga\"; Marga adalah sebuah desa ibu kota kecamatan di pelosok Kabupaten Tabanan, Bali) Di tempat puputan tersebut lalu didirikan Taman Pujaan Bangsa Margarana. "));
        }
        return data;
    }
}
